# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 04:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='Goods number')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
            ],
            options={
                'verbose_name': 'Order goods',
                'verbose_name_plural': 'Order goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Order number')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Trade number')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', 'success'), ('TRADE_CLOSED', 'timeout closed'), ('WAIT_BUYER_PAY', 'order created'), ('TRADE_FINISHED', 'order finished'), ('paying', 'wait to pay')], default='paying', max_length=30, verbose_name='Order status')),
                ('post_script', models.CharField(max_length=200, verbose_name='Order comment')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='Order amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='Pay time')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Shipping address')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='Signer')),
                ('singer_mobile', models.CharField(max_length=11, verbose_name='Mobile')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='ShippingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=0, verbose_name='Number')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='Goods')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
    ]
