# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 04:18
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Banner image')),
                ('index', models.IntegerField(default=0, verbose_name='Banner index')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
            ],
            options={
                'verbose_name': 'Banner goods',
                'verbose_name_plural': 'Banner goods',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='Goods UID')),
                ('name', models.CharField(max_length=100, verbose_name='Goods name')),
                ('click_num', models.IntegerField(default=0, verbose_name='Click number')),
                ('sold_num', models.IntegerField(default=0, verbose_name='Sold number')),
                ('fav_num', models.IntegerField(default=0, verbose_name='Favarite number')),
                ('goods_num', models.IntegerField(default=0, verbose_name='Goods number')),
                ('market_price', models.FloatField(default=0, verbose_name='Market price')),
                ('shop_price', models.FloatField(default=0, verbose_name='SHop price')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='Goods brief')),
                ('goods_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='Goods description')),
                ('ship_free', models.BooleanField(default=True, verbose_name='Is ship free')),
                ('goods_front_image', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='Front image')),
                ('is_new', models.BooleanField(default=False, verbose_name='Is new')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Is hot')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Category name', max_length=30, verbose_name='Category name')),
                ('code', models.CharField(default='', help_text='Category code', max_length=30, verbose_name='Category code')),
                ('desc', models.TextField(default='', help_text='Category description', verbose_name='Category description')),
                ('category_type', models.IntegerField(choices=[(1, 'First category'), (2, 'Second category'), (3, 'Third category')], help_text='Category type', verbose_name='Category type')),
                ('is_tab', models.BooleanField(default=False, help_text='Is navigation', verbose_name='Is navigation')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2017, 11, 1, 4, 18, 22, 665941), verbose_name='Add time')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Goods category',
                'verbose_name_plural': 'Goods categories',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Brand name', max_length=30, verbose_name='Brand name')),
                ('desc', models.TextField(default='', help_text='Brand description', max_length=200, verbose_name='Brand description')),
                ('image', models.ImageField(max_length=200, upload_to='brands/')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2017, 11, 1, 4, 18, 22, 666756), verbose_name='Add time')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='Goods category')),
            ],
            options={
                'db_table': 'goods_goodsbrand',
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='Goods image')),
            ],
            options={
                'verbose_name': 'Goods Image',
                'verbose_name_plural': 'Goods Image',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='Goods category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='Goods'),
        ),
    ]
